config/routes.rb
Playlist::Application.routes.draw do
  root to: 'entries#index'
  resources :entries

  get "index/download"


end

app/models/entry.rb
class Entry < ActiveRecord::Base
  validates :song, :artist, :album, presence: true
  validates_uniqueness_of :song, scope: :artist


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < InheritedResources::Base
  actions :new, :show, :index, :edit, :update
  before_filter :set_message, :only => [:update]

  def save_to_file(entry)
    playlist = 'playlist.txt'
    File.open(playlist, 'a+') do |f|
      f.puts "Song: #{@entry.song}  by  #{@entry.artist}  on the album #{@entry.album}"
    end
  end

  def create
    @entry = Entry.new(entry_params)
    if @entry.save
      flash[:notice] = "Your song was added"
      save_to_file(@entry)
      redirect_to entries_path
    else
      flash[:error] = "Your song wasn't added. Please check all info and try agian."
      render :new
    end
  end

  private
  def entry_params
    params.require(:entry).permit(:artist, :album, :song)
  end

  def set_message
    flash[:warning] = "Are you sure you want to overwrite this song information?"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/entries/_form.html.haml
%section
  .container
    .row
      .col-med-10-md-offset-1
        = bootstrap_form_for [@entry], html: {class: "form-horizontal"} do |f|
          %fieldset
            = f.text_field :artist
            = f.text_field :album
            = f.text_field :song
          %fieldset.actions.form-group
            .col-sm-6.col-md-offset-3
              = f.submit(@entry.new_record? ? 'Add Song' : 'Update Song', class: 'btn btn-default center-block')
-#
              %input(type="submit" value="Add Song" class="btn btn-default center-block")

app/views/entries/edit.html.haml
%header Edit Song Info
%well
  = render 'form'

app/views/entries/filepath.html.haml
%header Playlist
%containter
  %well
    .h3 Your playlist has been saved to the playlist.txt file
      

app/views/entries/index.html.haml
%header Playlist
%row
  =button_to "Add Music To Your Playlist", new_entry_path
  =button_to "Download Playlist to File", index_download_path
%container
  %table.table
    %table-responsive
      %tbody
        %tr
          %td.h2 Song
          %td.h2 Artist
          %td.h2 Album
        - @entries.each do |entry|
          %tr
            %td= entry.song
            %td= entry.artist
            %td= entry.album

app/views/entries/new.html.haml
%header Add New Song
%well
  = render 'form'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Playlist</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>